### ISSUE TITLE
番組移動で ジャンクション(NTFS)に 録画ファイルが移動されない

### ISSUE THREAD

**Issue by seijit** [dongaba/TVerRec#102]
[Windows/NTFS環境] 番組移動の処理で、移動先ディレクトリの配下でフォルダがジャンクションだった場合に、同名のフォルダが存在するにもかかわらず 録画ファイルが移動されない。ジャンクションのリンク先が参照されていない？

**Comment by seijit** [comment]
移動先ディレクトリには ネットワークドライブ(配下のディレクトリ)を指定しています。。

**Comment by dongaba** [comment]
Powershellではジャンクションは通常のディレクトリとは同じように扱えないのでそれが原因の可能性があります。
調査にお時間をいただければと思いますが、そもそも移動先がネットワークドライブ(あるいはその配下ディレクトリ)なのであれば、ジャンクションではなくネットワークドライブ上のPathで指定すれば良いと思われます。

例えば、ネットワークドライブ Nドライブ 上に TVerというフォルダがあって、そこに移動したい場合`N:\TVer`と指定するわけにはいかないのでしょうか?
ジャンクションを使わなければいけない理由は何でしょうか?

**Comment by seijit** [comment]
ジャンクションを使用している理由は、複数(15以上)のドライブ(ほぼHDD)で一つのドライブ(パス)を構成しているためです。
複数のドライブを使用している理由は、録画ファイルの容量がドライブの容量を大幅に超えているためです。

具体的には サーバーで録画ファイルを O:\DTV に保存しており、O:\DTV\Drama, O:\DTV\Anime などとジャンル分けをしていますが、この Drama や Anime がジャンクションになっています。ジャンクションのリンク先は C:\mnt\drive-1\DTV\Drama, C:\mnt\drive-2\DTV\Anime などとなっていて、フォルダにマウントされたドライブを参照しています。
この サーバーの O:\ を共有して \\server.local\o というパスに対して クライアントからアクセスしています。
#ネットワークドライブ(O:\)を割り当てていますが、割り当ては必須ではありません。

本事象では クライアントからサーバーのネットワーク共有 \\server.local\o\DTV\Drama を参照した場合に、
Windowsエクスプローラー や コマンドプロンプトdirコマンド の場合は 
\\server.local\o\DTV\Drama の ジャンクションDramaの リンク先C:\mnt\drive-1\DTV\Dramaが 「サーバー側で自動的に」解決されて \\server.local\o\DTV\Drama というパスで サーバーローカルの C:\mnt\drive-1\DTV\Drama にアクセスすることができます。

これと同じことが Powershell で 実装可能なのかどうか、、？
検索してみましたが、分かりませんでした。。。

**Comment by dongaba** [comment]
なるほど、事情はわかりました。
移動先には複数指定できるので、ジャンクションの対応ができるまでは(できるかわかりませんが)、複数あるドライブの全てを移動先に指定されてはいかがでしょうか?

https://github.com/dongaba/TVerRec/blob/master/conf/system_setting.ps1
の40行目に記載があるように、セミコロン区切りで複数指定ができます。
流石に15以上は指定したことはないのですが、理論上は問題なく動作するはずですので、お試しください。

**Comment by dongaba** [comment]
Wikiには明確に記載していなかったので、Wikiにも記載しました。
https://github.com/dongaba/TVerRec/wiki/%E5%9F%BA%E6%9C%AC%E7%9A%84%E3%81%AA%E8%A8%AD%E5%AE%9A

**Comment by dongaba** [comment]
もう1つ考えられる代替案としては、ジャンクションではなくシンボリックリンクを使ってみてはどうでしょうか?

**Comment by dongaba** [comment]
ちょっと調べてみましたが、簡単には対応で来なさそうです。
いただいたパスの例で試してみると、Powershellで移動先`\server.local\o\DTV`を参照した際に、Dramaは`C:\mnt\drive-1\DTV\Drama`という情報が取れるようです。
したがって、別のマシン(クライアント)から参照すると、クライアント上の`C:\mnt\drive-1\DTV\Drama`を探しに行ってしまうと思われ、ディレクトリが存在しないので失敗するようです。
これを解決する方法はぱっと思いつかないので、`C:\mnt\drive-1\DTV\Drama`などのフォルダをネットワークマウントして、そのネットワークドライブを移動先として複数指定するのが次善の策となるような気がします。

**Comment by seijit** [comment]
移動先ディレクトリは 複数指定できるんですね、Wikiの更新ありがとうございました。

**Comment by seijit** [comment]
＞フォルダをネットワークマウントして、そのネットワークドライブを移動先として複数指定するのが次善の策となるような気がします。

C:\mnt\drive-1\DTV\Drama の C:\mnt\drive-1 をネットワーク共有して
;\\server.local\drive-1\DTV を移動先ディレクトリに追加したところ、期待した動作が実現できました！

**Comment by seijit** [comment]
事象についてChatGPT4に質問してみたので回答を共有します。

Q.
Windowsエクスプローラー や コマンドプロンプトdirコマンド の場合は 
そのような問題は発生せずにアクセスすることができます。なぜでしょうか？

A.
Windowsエクスプローラーやコマンドプロンプトの `dir` コマンドでは、ネットワーク共有を経由した際にジャンクションが適切に解決される理由はいくつかあります。

1. **サーバー側での解決**: ネットワーク共有フォルダにアクセスするとき、クライアントからの要求はサーバー側で処理されます。サーバー側ではジャンクションが正しく解決され、適切なファイルシステムアクセスが提供されます。このため、エクスプローラーや `dir` コマンドはジャンクションのリンク先に問題なくアクセスできます。

2. **ファイルシステムの抽象化**: Windowsエクスプローラーや `dir` コマンドは、WindowsのファイルシステムAPIを使用してファイルシステム操作を行います。これにより、ジャンクションやシンボリックリンクの解決が透過的に行われます。一方、PowerShellの `Get-ChildItem` コマンドレットは、低レベルのファイルシステム操作を行い、ジャンクションの解決がクライアント側で行われるため、アクセスできない場合があります。

### 代替アプローチ

PowerShellでこの問題を回避するために、以下のアプローチを試すことができます。

1. **PowerShellのコマンドレットを使わずにシステムコマンドを呼び出す**: `cmd.exe` の `dir` コマンドをPowerShellから呼び出して、ジャンクションを解決する。

```powershell
$networkPath = "\\server.local\o\DTV"
$cmdOutput = cmd /c "dir $networkPath /s /b"
$cmdOutput
```

2. **PowerShellのRemotingを使用してサーバー側で実行する**: PowerShell Remotingを使用して、サーバー側でスクリプトを実行し、結果を取得する。

```powershell
$server = "server.local"
$scriptBlock = {
    param($path)
    Get-ChildItem -Path $path -Recurse -Force
}
Invoke-Command -ComputerName $server -ScriptBlock $scriptBlock -ArgumentList "O:\DTV"
```

この方法では、サーバー側でジャンクションが解決されるため、クライアント側での問題を回避できます。

これらのアプローチを試してみてください。最初の方法は簡単でありながら効果的で、特にPowerShell Remotingを設定する手間を省くことができます。

**Comment by seijit** [comment]
dirコマンドの案は一見よさそうですが、TVerRecはクロスプラットフォームなのですよね。
「Windowsならば」という条件分岐を入れることはできるけど、
そういう実装を このような特殊な環境のためにしていただくことは、妥当では無い。。。

**Comment by seijit** [comment]
当方としては下記いずれかで対応させていただこうと思います。

・ジャンクションを全てネットワーク共有して、移動先ディレクトリに全て追加する

・自ローカルに dirコマンドバージョンのパッチを当てる

**Comment by dongaba** [comment]
調査とご連絡をありがとうございます。
おっしゃるようにサーバ側でPowershellを動作させる前提やdirコマンドを呼び出す案は難しいと考えています。
dirコマンドを呼び出す案は、実際にはファイルの移動や削除などにも同様の考慮が必要となるため、実装するにしても実装範囲が広範になってしまうためです。

申し訳ありませんが、ジャンクションへの対応は難しいため、本件は未対応のままCloseとさせていただきます。

**Comment by dongaba** [comment]
調査とご連絡をありがとうございます。
おっしゃるようにサーバ側でPowershellを動作させる前提やdirコマンドを呼び出す案は難しいと考えています。
dirコマンドを呼び出す案は、実際にはファイルの移動や削除などにも同様の考慮が必要となるため、実装するにしても実装範囲が広範になってしまうためです。

申し訳ありませんが、ジャンクションへの対応は難しいため、本件は未対応のままCloseとさせていただきます。

**Comment by seijit** [comment]
dirコマンドバージョンの実装例を提示しておきます


move_video.ps1

```powershell
#移動先ディレクトリ配下のディレクトリ一覧を取得する関数 (Windows)
function Get-DirectoriesWithDir {
    param (
        [string[]]$paths
    )

    $results = @()
    foreach ($path in $paths) {
        # cmd.exeを呼び出してdirコマンドを実行し、その結果を取得
        $cmd = "cmd.exe /c dir `"$path`" /s /b /a:d"
        $directories = Invoke-Expression $cmd
        foreach ($dir in $directories) {
            $results += $dir
        }
    }
    return $results
}

#移動先ディレクトリ配下のディレクトリ一覧 (クロスプラットフォーム)
$moveToPathsHash = @{}
if ($script:saveBaseDir) {
    $script:saveBaseDirArray = $script:saveBaseDir.Split(';').Trim()
    
    if ($IsWindows) {
        # Windowsの場合
        $directories = Get-DirectoriesWithDir -paths $script:saveBaseDirArray
        foreach ($dir in $directories) {
            $dirName = Split-Path -Leaf $dir
            $moveToPathsHash[$dirName] = $dir
        }
    } else {
        # その他のプラットフォームの場合
        Get-ChildItem -LiteralPath $script:saveBaseDirArray -Directory -Recurse | ForEach-Object { $moveToPathsHash[$_.Name] = $_.FullName }
    }
}
```

**Comment by seijit** [comment]
特殊な環境向けに対して真摯にご回答いただき、ありがとうございました。

**Comment by dongaba** [comment]
コードサンプルをありがとうございます。素朴な疑問なのですが、ディレクトリの一覧がこれで取得できるのはわかるのですが、その後のファイルの移動もcmd.exeを使うようにしないといけない気がしますが、ファイル移動は改変しなくてもできている状態ですか?

**Comment by seijit** [comment]
提示させていただいたコードサンプルで ダウンロードファイルを移動する処理は、期待通りに動作しています。

**Comment by seijit** [comment]
後続の「ダウンロードファイルを移動」は なぜ cmd.exe を使うように改変しなくても期待通りに処理できているのか、
分からなかったので聞いてみました。

**Comment by seijit** [comment]
「ダウンロードファイルを移動」セクションが期待通りに動作する理由は、PowerShellの `Move-Item` コマンドレットがWindowsエクスプローラーや `dir` コマンドと同様に、ジャンクションをサポートし、リンク先のパスを正しく解決するためです。以下にいくつかの理由を詳しく説明します。

### 1. ジャンクションのサポート
PowerShellの `Move-Item` コマンドレットは、ジャンクションやシンボリックリンクを正しく解決します。したがって、`Move-Item` コマンドレットはリンク先のターゲットパスに直接アクセスできます。これは、Windowsエクスプローラーや `dir` コマンドが同じ方法でリンクを解決するためです。

### 2. PowerShellのファイルシステムAPI
PowerShellはWindowsのネイティブなファイルシステムAPIを使用しています。このAPIはジャンクションやシンボリックリンクを透過的に処理します。したがって、`Move-Item` コマンドレットはリンク先を自動的に解決し、ファイル移動を正しく行います。

### 3. PowerShellとWindowsエクスプローラーの一貫性
Windowsエクスプローラーや `dir` コマンドと同様に、PowerShellのファイル操作コマンドはWindowsオペレーティングシステムのファイルシステムAPIを利用しています。これにより、一貫した動作が保証されます。具体的には、リンクの解決やファイルシステムの操作が同じ方法で行われるため、PowerShellでも期待通りの結果が得られます。

### スクリプトの詳細

あなたのスクリプトでは、次のようにファイル移動を行っています。

```powershell
# 同名ディレクトリが存在する場合は配下のファイルを移動
if (Test-Path $moveFromPath) {
    Write-Output ('　{0}\(*.mp4;*.ts)' -f $moveFromPath)
    try { $null = Move-Item -Path ('{0}\*' -f $moveFromPath) -Include @('*.mp4', '*.ts') -Destination $moveToPath -Force }
    catch { Write-Warning ('⚠️ 移動できないファイルがありました - {0}' -f $moveFromPath) }
}
```

ここでは、`Test-Path` コマンドレットでディレクトリの存在を確認し、`Move-Item` コマンドレットでファイルを移動しています。この操作は、ジャンクションを正しく解決するため、リンク先の実際のディレクトリに対して操作を行います。そのため、`Move-Item` コマンドレットは期待通りに動作します。

### まとめ
PowerShellの `Move-Item` コマンドレットが期待通りに動作する理由は、WindowsのネイティブなファイルシステムAPIを利用しており、ジャンクションやシンボリックリンクを正しく解決するためです。これにより、ファイル移動操作がWindowsエクスプローラーや `dir` コマンドと同様に正しく行われます。

**Comment by seijit** [comment]
なんだか少し 矛盾した部分もある回答ですが、つまり Get-ChildItem コマンドレット の問題のようです。

**Comment by seijit** [comment]
「移動先ディレクトリ配下のディレクトリ一覧」の処理を分解し、Windowsの場合を別の関数に分けることは、コードの読みやすさとメンテナンス性を向上させるために良い方法です。以下のように、関数 Get-DirectoriesOnWindows を作成し、メインの関数から呼び出すようにします。


```
# Windowsのディレクトリ一覧を取得する関数
function Get-DirectoriesOnWindows {
    param (
        [string[]]$paths
    )

    $results = @()
    foreach ($path in $paths) {
        $cmd = "cmd.exe /c dir `"$path`" /s /b /a:d"
        $directories = Invoke-Expression $cmd
        foreach ($dir in $directories) {
            $results += $dir
        }
    }
    return $results
}

# プラットフォームに応じたディレクトリ一覧を取得する関数
function Get-DirectoriesWithPlatformCheck {
    param (
        [string[]]$paths
    )

    $results = @()
    if ($IsWindows) {
        # Windowsの場合
        $results = Get-DirectoriesOnWindows -paths $paths
    } else {
        # その他のプラットフォームの場合
        foreach ($path in $paths) {
            $directories = Get-ChildItem -LiteralPath $path -Directory -Recurse
            foreach ($dir in $directories) {
                $results += $dir.FullName
            }
        }
    }
    return $results
}

# 移動先ディレクトリ配下のディレクトリ一覧
$moveToPathsHash = @{}
if ($script:saveBaseDir) {
    $script:saveBaseDirArray = $script:saveBaseDir.Split(';').Trim()
    $directories = Get-DirectoriesWithPlatformCheck -paths $script:saveBaseDirArray
    foreach ($dir in $directories) {
        $dirName = Split-Path -Leaf $dir
        $moveToPathsHash[$dirName] = $dir
    }
}

```

**Comment by seijit** [comment]
すいません、ChatGPTの回答をポンと置くと私が言ったみたいでややこしいので消しました。下記に更新したコードサンプルを提示します。ダウンロードファイルを移動する処理が、期待通りに動作しました。

```
# Windowsのディレクトリ一覧を取得する関数
function Get-DirectoriesOnWindows {
    param (
        [string[]]$paths
    )

    $results = @()
    foreach ($path in $paths) {
        $cmd = "cmd.exe /c dir `"$path`" /s /b /a:d"
        $directories = Invoke-Expression $cmd
        foreach ($dir in $directories) {
            $results += $dir
        }
    }
    return $results
}

# プラットフォームに応じたディレクトリ一覧を取得する関数
function Get-DirectoriesWithPlatformCheck {
    param (
        [string[]]$paths
    )

    $results = @()
    if ($IsWindows) {
        # Windowsの場合
        $results = Get-DirectoriesOnWindows -paths $paths
    } else {
        # その他のプラットフォームの場合
        foreach ($path in $paths) {
            $directories = Get-ChildItem -LiteralPath $path -Directory -Recurse
            foreach ($dir in $directories) {
                $results += $dir.FullName
            }
        }
    }
    return $results
}

# 移動先ディレクトリ配下のディレクトリ一覧
$moveToPathsHash = @{}
if ($script:saveBaseDir) {
    $script:saveBaseDirArray = $script:saveBaseDir.Split(';').Trim()
    $directories = Get-DirectoriesWithPlatformCheck -paths $script:saveBaseDirArray
    foreach ($dir in $directories) {
        $dirName = Split-Path -Leaf $dir
        $moveToPathsHash[$dirName] = $dir
    }
}
```

**Comment by dongaba** [comment]
ありがとうございます。
せっかくコードサンプルもいただき動作確認もしていただいたので、いただいたコードを取り込みできるように対応しようと思います。
Issueを再度Openに戻します。

**Comment by seijit** [comment]
やったー、ありがとうございます！

**Comment by dongaba** [comment]
よく考えたら、いただいたコードだと不完全な可能性があることに気がしてきました。
移動先がWindows機でジャンクションを使っている場合に問題が発生するのだと思いますが、この場合、クライアント側がWindowsだけでなく、MacやLinuxも想定しないといけないと思われます。(未確認)
上記仮定が正しいとすると、クライアントがWindowsかどうかを判定してcmd.exeを呼び出すだけでは不十分な可能性があり、サーバ側のOSを判定する必要があるような。。
当方に検証用の環境がなくすぐに確認できないので、ちょっと対応の可否を判断するのにお時間をいただくかもしれません。

**Comment by seijit** [comment]
「番組移動処理で、移動先ディレクトリにジャンクションが存在する場合に対応する」が 本件主題です。

＞この場合、クライアント側がWindowsだけでなく、MacやLinuxも想定しないといけないと思われます。(未確認)
Windowsクライアントが本件主題に対応できることは確認済みだが、
macOS/Linuxでは未確認だ、というのがご指摘で認識あっていますか？

当方環境 macOS Sonoma 14.5 で 本件主題に対応できることを確認しました。

Linux は環境がないのですが、Dockerにトライすれば確認になりますか？

**Comment by seijit** [comment]
提示済みサンプルコードは、プラットフォームに関して、
サーバーなのかクライアントなのか曖昧な点があると思いますので、
下記の通り更新しました（function名とコメント）。
動作確認済みです。

```powershell:move-video.ps1
# 実行環境（クライアント）がWindowsの場合にディレクトリ一覧を取得する関数
function Get-DirectoriesForWindowsClient {
    param (
        [string[]]$paths
    )

    $results = @()
    foreach ($path in $paths) {
        $cmd = "cmd.exe /c dir `"$path`" /s /b /a:d"
        $directories = Invoke-Expression $cmd
        foreach ($dir in $directories) {
            $results += $dir
        }
    }
    return $results
}

# 実行環境（クライアント）に応じてディレクトリ一覧を取得する関数
function Get-DirectoriesBasedOnClientPlatform {
    param (
        [string[]]$paths
    )

    $results = @()
    if ($IsWindows) {
        # 実行環境（クライアント）がWindowsの場合
        $results = Get-DirectoriesForWindowsClient -paths $paths
    } else {
        # 実行環境（クライアント）がその他のプラットフォームの場合
        foreach ($path in $paths) {
            $directories = Get-ChildItem -LiteralPath $path -Directory -Recurse
            foreach ($dir in $directories) {
                $results += $dir.FullName
            }
        }
    }
    return $results
}

# 移動先ディレクトリ配下のディレクトリ一覧
$moveToPathsHash = @{}
if ($script:saveBaseDir) {
    $script:saveBaseDirArray = $script:saveBaseDir.Split(';').Trim()
    $directories = Get-DirectoriesBasedOnClientPlatform -paths $script:saveBaseDirArray
    foreach ($dir in $directories) {
        $dirName = Split-Path -Leaf $dir
        $moveToPathsHash[$dirName] = $dir
    }
}
```

**Comment by dongaba** [comment]
ありがとうございます。つまり、少なくともMacにおいては、サーバ側の移動先がジャンクションであっても、ジャンクションの参照先をちゃんと解決できるということなのですね。
ジャンクションが解決できないのはWindows環境固有の問題と考えられそうですね。
Linux環境はDockerでシミュレーションできますが、Dockerから見た場合の移動先がDockerで抽象化されてしまっていると、検証としては不十分かもしれません。(Linuxから見た移動先のジャンクションの解決が、Linux側ではなくDockerやDockerが稼働するOS上でされてしまう可能性があるような気がします。このあたり詳しくないのでよくわからないのですが。。。)

**Comment by seijit** [comment]
詳しくないのですが、WindowsでのDocker/Hyper-Vとか確認にならないかもしれないですね。
macOSでも同様？ 実機に Linux をインストールするしかない。。？
なにか Live CD (USB) みたいな環境でも いいのでしょうか？ PowerShell Core の実装次第かもしれませんが。。
ご推奨の確認環境は ありますか？

**Comment by seijit** [comment]
詳しくないのですが、WindowsでのDocker/WSL2 とか確認にならないかもしれないですね。
macOSでも同様？ 実機に Linux をインストールするしかない。。？
なにか Live CD (USB) みたいな環境でも いいのでしょうか？ 
ネットワーク経由なら確認になりそうな気もしますが、それも PowerShell Core の実装次第かもしれませんね。
ご推奨の確認環境は ありますか？

**Comment by dongaba** [comment]
Hyper-Vであれば十分検証として成立します。Live CDでももちろんOKです。
Docker、WSL2はファイルシステムへのアクセスがDockerやWSLで抽象化されてしまうので微妙かもしれません。
WSLであっても、mount.cifsコマンド等でマウントしていただければ十分検証可能ですが、WindowsのネットワークドライブをWSLにマウントした場合は検証としては不十分だと考えられます。

**Comment by seijit** [comment]
了解です。
Hyper-V か VMware か LiveCD で確認をトライします。Ubuntuとかでしょうか。
Linux門外漢なので少々お時間ください。

**Comment by seijit** [comment]
Ubuntu 22.04.4 LTS の USB起動環境で確認しました。
結果、Windowsの実行環境と同様に
Ubuntuの実行環境ではリモートのジャンクションを解決できませんでした。

**Comment by seijit** [comment]
下記に更新したコードサンプルを提示しますので、レビューをお願いします。
番組移動処理が、下記環境で期待通りに動作しました。

Ubuntu 22.04.4 LTS
macOS Sonoma 14.5
Windows10 Pro 22H2


```
# 実行環境（クライアント）がWindowsの場合にディレクトリ一覧を取得する関数
function Get-DirectoriesForWindowsClient {
	param (
			[string[]]$paths
	)

	$results = @()
	foreach ($path in $paths) {
			$cmd = "cmd.exe /c dir `"$path`" /S /B /A:D"
			$directories = Invoke-Expression $cmd
			foreach ($dir in $directories) {
					$results += $dir
			}
	}
	return $results
}

# 実行環境（クライアント）がLinuxまたはmacOSの場合にディレクトリ一覧を取得する関数
function Get-DirectoriesForUnixClient {
	param (
			[string[]]$paths
	)

	$results = @()
	foreach ($path in $paths) {
			$cmd = "find `"$path`" -type d"
			$directories = Invoke-Expression $cmd
			foreach ($dir in $directories) {
					$results += $dir
			}
	}
	return $results
}

# 実行環境（クライアント）に応じたディレクトリ一覧を取得する関数
function Get-DirectoriesBasedOnClientPlatform {
	param (
			[string[]]$paths
	)

	$results = @()
	if ($IsWindows) {
			# 実行環境（クライアント）がWindowsの場合
			$results = Get-DirectoriesForWindowsClient -paths $paths
	} else {
			# 実行環境（クライアント）がLinuxまたはmacOSの場合
			$results = Get-DirectoriesForUnixClient -paths $paths
	}
	return $results
}

# 移動先ディレクトリ配下のディレクトリ一覧
$moveToPathsHash = @{}
if ($script:saveBaseDir) {
	$script:saveBaseDirArray = $script:saveBaseDir.Split(';').Trim()
	$directories = Get-DirectoriesBasedOnClientPlatform -paths $script:saveBaseDirArray
	foreach ($dir in $directories) {
			$dirName = Split-Path -Leaf $dir
			$moveToPathsHash[$dirName] = $dir
	}
}
```

**Comment by seijit** [comment]
コメントを修正し、関数名を戻しました、
処理のコードは変更していません。

コメント：コードの必要性を記載
関数名：元の関数名を復帰

```
# Windows環境でディレクトリ一覧を取得
function Get-DirectoriesOnWindows {
    param (
        [string[]]$paths
    )

    $results = @()
    foreach ($path in $paths) {
        # dirコマンドで再帰的にディレクトリ一覧を取得
        $cmd = "cmd.exe /C dir `"$path`" /S /B /A:D"
        $directories = Invoke-Expression $cmd
        foreach ($dir in $directories) {
            $results += $dir
        }
    }
    return $results
}

# Linux/macOS環境でディレクトリ一覧を取得
function Get-DirectoriesOnUnix {
    param (
        [string[]]$paths
    )

    $results = @()
    foreach ($path in $paths) {
        # findコマンドで再帰的にディレクトリ一覧を取得
        $cmd = "find `"$path`" -type d"
        $directories = Invoke-Expression $cmd
        foreach ($dir in $directories) {
            $results += $dir
        }
    }
    return $results
}

# 実行環境に応じてディレクトリ一覧を取得
# Get-ChildItemコマンドレットがジャンクションのパスを解決できない問題を回避
function Get-DirectoriesWithPlatformCheck {
    param (
        [string[]]$paths
    )

    $results = @()
    if ($IsWindows) {
        $results = Get-DirectoriesOnWindows -paths $paths
    } else {
        $results = Get-DirectoriesOnUnix -paths $paths
    }
    return $results
}
```
