### ISSUE TITLE
リスト作成を実行でエラーメッセージが表示される

### ISSUE THREAD

**Issue by dongaba** [dongaba/TVerRec#134]
3.2.5から初めて使わせていただいております。海外在住なので、たいへんありがたいツールです。作者様には感謝しかありません。

なお、一点問題が発生したので、回避策と合わせてご報告させていただきます。もし同じような問題に遭遇された方がいらした場合、ご参考になれば幸いです。

1.  3.2.5を新規DL後、リスト作成を実行
→ Cannot bind argument to parameter 'DifferenceObject' because it is null._
というメッセージが表示され、リストファイルに動画が追加されませんでした。数回試しましたが同じ結果です。

2. 3.2.4を別ディレクトリにDLし、リスト作成を実行
→ 問題なくリストに動画が追加されました。

3. 3.2.4で作成したリストを3.2.5のディレクトリにコピーし、3.2.5を起動してリスト作成を実行
→ 問題なくリストに動画が追加され、以降は3.2.5のみで問題なく使用できています。

以上です。

_Originally posted by @Harry-O in https://github.com/dongaba/TVerRec/discussions/129#discussioncomment-11586374_

**Comment by dongaba** [comment]
3.2.6で対応したつもり

**Comment by Harry-O** [comment]
確認しました。ありがとうございます。
