### ISSUE TITLE
移動先ディレクトリに移動されない

### ISSUE THREAD

**Issue by masahiko-imai** [dongaba/TVerRec#149]
お世話になります。
とても便利なツールを作成下さりありがとうございます。
Windows、Linuxで動作を確認したのですが、どちらもダウンロードおよびファイルの検証までは正常に動くのですが、移動先ディレクトリにファイルが移動されません。
どうやら、移動先ディレクトリにダウンロード先ディレクトリと同じ名前のフォルダがあれば、そこにファイルを移動する仕様のようですが、移動先ディレクトリにフォルダが作成されず、移動されないようです。
ご確認いただきたく、よろしくお願いします。

**Comment by dongaba** [comment]
Windows/Linuxの双方で確認しましたが問題を再現できませんでした。もう少し詳しく問題を教えていただけますか。
また、設定がうまくいっていない可能性があるので、`user_setting.ps1`内で以下の3つがどの様に設定されているかを教えていただけますか。

- `$script:downloadBaseDir`
- `$script:downloadWorkDir`
- `$script:saveBaseDir`

**Comment by masahiko-imai** [comment]
クイックレスポンスありがとうございます。
下記、Windowsです。
![GUIでの設定](https://github.com/user-attachments/assets/fc5c98cb-e68f-4cfb-a8da-e7e7d34670dc)
![user_setting.ps1](https://github.com/user-attachments/assets/2872c3f4-a291-40d2-b9b3-73650ce53edb)

下記、Linuxです。
Linuxと言いつつdockerで、downloadが/mnt/Tempだと/dev/shmが溢れてダウンロードできなかったので変更しています。
![image](https://github.com/user-attachments/assets/f6587ff6-587e-4294-8a77-a566c0527643)

よろしくお願いします。

**Comment by dongaba** [comment]
拝見する限り特に問題点は見当たらないのですが、`E:\tverrec\done`には`E:\tverrec\download`にあるのと同名ののフォルダがあるけど番組が移動されないということでしょうか?

以下のページの`4.ダウンロード番組の移動`に説明されているように、`E:\tverrec\download`に番組のディレクトリが空でも良いので存在しないとファイルは移動されませんが、`E:\tverrec\download`配下に番組名のフォルダは存在しているでしょうか?
https://github.com/dongaba/TVerRec/wiki/%E5%88%9D%E6%9C%9F%E8%A8%AD%E5%AE%9A%E3%83%BB%E7%92%B0%E5%A2%83%E8%A8%AD%E5%AE%9A%E3%81%AE%E6%96%B9%E6%B3%95

**Comment by masahiko-imai** [comment]
なるほど。私の認識が間違っていたようです。
移動先のフォルダには、番組名のフォルダが予め必要であるという仕様なのですね。承知しました。
本件、クローズさせていただきます。
