### ISSUE TITLE
2.6.2仕様変更？

### ISSUE THREAD

**Issue by igonodesi07** [dongaba/TVerRec#20]
a.download_video.bat使用してるのですが
ダウンロード先と保存先がなんか変更ありました？
いきなり保存先に落ちてきます

**Comment by igonodesi07** [comment]
どうもすみませんでした、こちらのチョンボやったみたいです、昨日試したところ問題なしでした、お騒がせいたしました。
このソフトいいですね、すごーく気に入ってます、ありがとうございます

**Comment by dongaba** [comment]
では不具合ではないということで。
