### ISSUE TITLE
I had some problems downloading individual videos

### ISSUE THREAD

**Issue by csmagics** [dongaba/TVerRec#24]
Forgive me, I don't use Japanese, I used the translator in order to read the wiki, did the installation and setup, but some pop-ups happened. And the download was not carried out. Is there something wrong with me?

I'm using macOS and I installed youtube dl yt-dlp ffmpeg via brew.

My settings are

$script:downloadBaseDir = '/Users/xxxx/TVerRec/download'
$script:downloadWorkDir = '/var/tmp'
$script:saveBaseDir = ''

Whenever I run . /z.download_single_video.sh there is a popup
 “未能打开文稿“youtube-dl”。文本编码Unicode (UTF-8)不适用。
该文件可能已使用了不同的文本编码来存储，或者可能不是文本文件。”

The pop-up I would click on confirm, ignore it, and then enter the web link to the video I was watching, for example " https://tver.jp/episodes/ep70asre26", and then the program would print out the video information and it would create a folder, but after that nothing would happen and it would continue to let I'll type in the link

**Comment by dongaba** [comment]
I would assume you don't have the right permission to execute youtube-dl or yt-dlp.
Please make sure to set executable permission to youtube-dl or yt-dlp like below.
`chmod a+x /path/to/youtube-dl` or `chmod a+x /path/to/yt-dlp`

Or another possibility is that TVerRec does not recognize where the youtube-dl or yt-dlp command is located as TVerRec is expecting youtube-dl or yt-dlp to be located under `bin` directory.
For this scenario, you can either 1. create a symbolic link under `bin` directory or 2. specify the path for youtube-dl or yt-dlp in a setting file.
I would recommend going with #1 as this will make sure TVerRec always refers to the latest youtube-dl or yt-dlp which might be updated by brew in the future.
You can create a symbolic link under `bin` directory by typing below command.
`ln -s /path/to/youtube-dl /path/to/TVerRec/bin` or `ln -s /path/to/yt-dlp /path/to/TVerRec/bin`

**Comment by csmagics** [comment]
@dongaba 
Thanks for your great help, I solved the download problem.
I found that the default bin folder was under the project folder and the automatically downloaded file would not give execute permission.
I set the path of the bin to /usr/local/bin/ and it downloaded fine.
-----------------------------------------------------------------
But I found a new small problem, setting $script:saveBaseDir = '/Users/xxxx/TVerRec/savedir', but the file is not stored to saveBaseDir.
This makes me a bit confused.
After reading the wiki, I think the file goes through downloadWorkDir -> downloadBaseDir -> saveBaseDir and then the file is stored.
And to be honest I don't see why downloadBaseDir is needed

**Comment by dongaba** [comment]
Thanks for your feedback.
The reason why donwloadBaseDir exists is that when you specify a specific keyword and/or genre TVerRec will download all video that matches the keyword and/or genre.
However, sometimes the user does not want to save all of them, but rather picks some specific video and/or series.
Hence, downloadBaseDir is something like a temporary directory that stores all downloaded videos.
On the other hand, saveBaseDir is more like a permanent archive directory that retains the video you really want to retain.
If you don't think this specification does not make sense, then you can simply specify a blank directory for saveBaseDir, that way all of the downloaded video will retain in downloadBaseDir.
Hope this explanation helps you understand and understand my intention.

**Comment by csmagics** [comment]
@dongaba 
Great design. But I use /z.download_single_video.sh to download the video, but the file is not moved to saveBaseDir, why? And as you said I can selectively store videos to saveBaseDir, I don't see how to set this part

**Comment by dongaba** [comment]
z.download_single_video.sh does not move the file from downloadBaseDir to saveBaseDir.
However, you can still move the vide from downloadBaseDir to saveBaseDir by using d.move_video.sh.
d.move_video.sh is designed to move video from downloadBaseDir to saveBaseDir whenever the directory name under downloadBaseDir matches to the sub-directory name under saveBaseDir.
Hence you first have to create a sub-directory under saveBaseDir or move the direcotyr from downloadBaseDir to saveBaseDir.

**Comment by csmagics** [comment]
@dongaba 
そうです Thank you for your patience. Your software works well and is cleverly designed. Incidentally, by looking up Japanese, I found out it is Agglutinative language, so translation and learning makes me feel more unfamiliar. I am very happy that I have gained a new understanding of Japanese.

**Comment by dongaba** [comment]
Good to hear all of your problems has been resolved.
Hopefully, I may try to prepare an English version of the instructions, but unfortunately, I don't have enough time so far.
