### ISSUE TITLE
機能の追加、改善要望などはこちら

### ISSUE THREAD

**Issue by kirakiraniconico** [dongaba/TVerRec#46]
最近，TVerRecを使用させていただいている者です。
ファイルをmp4ではなく，TVerのオリジナルの短い時間のtsファイルと同じtsファイルとすることはできないでしょうか？
ts -> mp4とするときの画質の劣化と音ズレの懸念があるためです。
ご検討，よろしくお願いいたします。

**Comment by dongaba** [comment]
動画ファイルのダウンロードはyoutube-dlに任せていますが、youtube-dlにtsファイルをダウンロードするオプションがあれば可能かもしれません。
ただ、ざっと調べた感じやり方はなさそうに思いますが、youtube-dlのオプション指定でtsファイルをダウンロードする方法があるのであれば、そのオプション指定を教えていただければ対応の可否を判断できます。
現時点では当方ではやり方不明のためCloseとさせていただきます。

**Comment by dongaba** [comment]
m3u8ファイルやmpdファイルを使ってffmpegでtsファイル形式でダウンロードすることや、yt-dlpでts形式で出力することができるようです。
ただ、当方この領域に詳しくなくこれで音ズレを解消できるのかはわかりません。
メタ情報や字幕等の埋め込みはできなくなりますが、tsファイルで保存するオプションの提供を検討中です。

**Comment by dongaba** [comment]
3.2.0でtsファイルで保存できるようにしてみました。
私自身はtsファイルのニーズがないのでこれで問題が解決しているかはよくわからないのですが、よければ試してみてください。
