### ISSUE TITLE
DL開始時にyoutube-dl.exeがすぐに終了し、番組がDLされず履歴が残ります

### ISSUE THREAD

**Issue by KazusaTomoe** [dongaba/TVerRec#47]
いつも大変お世話になっております。
月曜日に更新が行われてから、番組のダウンロードができなくなりました。
TverREC GUI事態きどうできなくなり、2.9.3を手動で新規ダウンロードしてすべて新しく設定し直し GUI版を起動することは成功しました。
個別ダウンロードから、TVerの番組URLを貼り付けしOKをクリックすると、動作はしているのですが、youtube-dl.exeがすぐに終了し、ダウンロード履歴だけが追加されダウンロードフォルダには番組名のフォルダは作られていますが中身は空の状態です。
いろいろな設定をすべて見直しましたが、どうしてもこれ以上前へ進めずご報告に参りました。
何か問題点や変更すべき箇所がございましたらお教えいただきたく存じます。
以上、何卒よろしくお願い申し上げます。

**Comment by dongaba** [comment]
個別ダウンロードにバグを見つけて対処しました。
2.9.4で再度ご確認いただけますでしょうか。

**Comment by KazusaTomoe** [comment]
dongaba様
早速のご対応ありがとうございました。
2.9.4をダウンロードさせていただき、すべて新規設定し、無事GUIを立ち上げ各ソフトのダウンロードが行われ、個別ダウンロード用のポップアップが出ましたので、TVerのURLを張りダウンロードを開始しましたが、今までと同じくyoutube-dl.exeがすぐに終了し、ダウンロード履歴だけが追加されダウンロードフォルダには番組名のフォルダは作られていますが中身は空の状態でした。ほかにチェックする箇所などありますでしょうか？
何卒宜しくお願い申し上げます。

以下がDL時に入りましたログにおなります。

❗ youtube-dlが古いため更新します。
　Local version: 
　Latest version: 2023.10.13
youtube-dlの最新版をダウンロードします
💡 youtube-dlをversion2023.10.13に更新しました。

❗ ffmpegが古いため更新します。
　Local version: 
　Latest version: n6.0-36-gc5039e158d
ffmpegの最新版x64用をダウンロードします
ダウンロードしたffmpegを解凍します
解凍したffmpegを配置します
中間ディレクトリと中間ファイルを削除します
💡 ffmpegをversionn6.0-36-gc5039e158d-20231025に更新しました。
https://tver.jp/episodes/epgvny4dnl
https://tver.jp/episodes/epgvny4dnl
　番組名:　 Ep1 私にとってセックスは、生きている証だ。
　放送日:　 2023年08月20日放送
　テレビ局: ABCテレビ
　配信終了: 10/30/2023 23:59:00
💡 ダウンロードするファイルをダウンロード履歴に追加します


---------------------------------------------------------------------------
ダウンロード処理を終了しました。                                           
---------------------------------------------------------------------------

フォルダには番組名のフォルダが中身が奈良の状態で置かれており、youtube-dl.exeの動作はほぼ見られませんでした。

**Comment by dongaba** [comment]
もし設定ファイルを手作業で編集されているのであれば、GUIから設定して保存してみていただけませんか。

**Comment by KazusaTomoe** [comment]
お忙しい中ご確認ありがとうございました。
再度、2.9.4を新規で置き直し、Setting.cmd より各設定を行い、完了させ、TVerRec.cmdよりGUIを出しました。
前回まで試していた番組内容に不適切な言葉がありましたので別番組を個別ダウンロードにてURLを張り開始しました。
残念ながら同じ結果となりました。
src フォルダのps1ファイルはプロパティから常に許可にしています。
ダウンロードされたyoutube-dl.exeは、プロパティ-セキュリティから全ユーザーフルコントロールに変更しています。
大変お手間を取れ背てしまい申し訳ありませんが、ほかにチェックする箇所などありますでしょうか？
youtube-dl.exeが立ち上がっても何も行わず終了してしまう状態が確認できております。
何卒宜しくお願い申し上げます。


❗ youtube-dlが古いため更新します。
　Local version: 
　Latest version: 2023.10.13
youtube-dlの最新版をダウンロードします
💡 youtube-dlをversion2023.10.13に更新しました。

❗ ffmpegが古いため更新します。
　Local version: 
　Latest version: n6.0-36-gc5039e158d
ffmpegの最新版x64用をダウンロードします
ダウンロードしたffmpegを解凍します
解凍したffmpegを配置します
中間ディレクトリと中間ファイルを削除します
💡 ffmpegをversionn6.0-36-gc5039e158d-20231026に更新しました。
https://tver.jp/episodes/epjfbka0rf
https://tver.jp/episodes/epjfbka0rf
　番組名:　 一子相伝のVシネ風パフェ【ノッコン寺田】
　放送日:　 2023年10月26日放送
　テレビ局: テレビ大阪
　配信終了: 11/02/2023 12:12:59
💡 ダウンロードするファイルをダウンロード履歴に追加します


---------------------------------------------------------------------------
ダウンロード処理を終了しました。                                           
---------------------------------------------------------------------------

**Comment by dongaba** [comment]
私の環境ではダウンロードできるんですよね。。
youtube-dlの画面がすぐに閉じてしまうとのことですが、画像を取れたりしないでしょうか。
user_setting.ps1で`$script:windowShowStyle = 'Normal'`とするとyoutube-dlのウィンドウが最小化されないのでエラーメッセージなど確認できればいいのですが。。
![image](https://github.com/dongaba/TVerRec/assets/83079591/50bc7645-7b1e-4b1e-9d02-ee67db4d1b3b)

**Comment by dongaba** [comment]
TVerRecのフォルダが`Program File`というフォルダ配下にあるようですが、フォルダ名にスペースが入っているためにエラーとなっている可能性がありそうです。
Cドライブ直下などフォルダ名にスペースを含まない場所に移動して再確認していただけませんか。

**Comment by KazusaTomoe** [comment]
dongaba様
このたびは、貴重なお時間に大変お手数おかけし申し訳ありませんでした。
C:\TVerRec\TVerRec-2.9.4
フォルダ構成を上記に改め無事GUIによる個別ダウンロードを行えることを確認いたしました。
何度か更新の際に動かなくことはありましたが、今回問題となりましたフォルダにて再ダウンロード、再構成にてダウンロードが行えており、youtube-dlのウィンドウの最小化により原因を確認することをできておらず誠に申し訳ありませんでした。
改めて、貴重なお時間ご指導、ご確認誠にありがとうございました。

**Comment by dongaba** [comment]
問題解決できてよかったです。Closeしますね。
