### ISSUE TITLE
user_setting.ps1の設定が読み込まれない

### ISSUE THREAD

**Issue by un-nerv** [dongaba/TVerRec#52]
$script:dbDir = "/content/db"
の設定だけがuser_setting.ps1から読み込まれませんでした。
windows unix環境両方で状況は変わりませんでした。

**Comment by un-nerv** [comment]
linux環境はcolaboratoryのubuntuにて調べました

**Comment by dongaba** [comment]
```
#----------------------------------------------------------------------
#	以下は変更を推奨しない設定。変更の際は自己責任で。
#----------------------------------------------------------------------
```
と記載があります通り、変更することを想定していません。
が、直近でその辺りのコードを少し変えたのでリリース版ではなく、最新版をダウンロードして確認してみていただけますでしょうか。
読み込んでいないとは考えにくいので、どのような症状が出るのか教えていただければ調査に役立ちます。

**Comment by dongaba** [comment]
2.9.8で関連コードを変更したので再度ご確認ください。
