### ISSUE TITLE
keyword.conf の読み取りについて

### ISSUE THREAD

**Issue by ngsaki** [dongaba/TVerRec#95]
最近このツールの存在を知り、便利に使っております。ありがとうございます。

keyword.conf に誤って epsodes/epxxxxxxxx を指定して dounload_bulk を起動すると
全番組？のダウンロードが始まってしまうようです。
epsodes は無視する仕様で良いので、検討していただければと思います。

**Comment by dongaba** [comment]
全番組をダウンロードしているわけではなく、`epsodes/epxxxxxxxx`というキーワードでキーワード検索してしまっているようです。
3.2.0で修正します。もしどうしても困っているようであれば、devチャネルから最新版をダウンロードしてご利用ください。

**Comment by ngsaki** [comment]
確認ありがとうございます。
指定しなければ大丈夫ですので、
アップデートをお待ちしてます！

2024年6月20日(木) 5:55 dongabacho ***@***.***>:

**Comment by dongaba** [comment]
3.2.0をリリースしましたのでCloseします。
